### ISSUE TITLE
Port mapping not working as documented

### ISSUE THREAD

**Issue by xcurry** [rhuss/docker-maven-plugin#118]
According the the manual, you can have <port>18080:8080</port>. However doing <port>8080:80</port> gives this error:

Caused by: java.lang.NumberFormatException: For input string: "8080:80"

**Comment by rhuss** [comment]
Thanks for the report. Could please post the plugin's version and the configuration snippet which caused this error ?

Thanks!

**Comment by xcurry** [comment]
`
        <groupId>org.jolokia</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.11.2</version>
`

and

`
               <ports>
                  <port>80:8080</port>
                  <port>8081</port>
                </ports>
`

**Comment by xcurry** [comment]
Caused by: java.lang.NumberFormatException: For input string: "80:8080"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.jolokia.docker.maven.assembly.DockerFileBuilder.expose(DockerFileBuilder.java:181)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createDockerFileBuilder(DockerAssemblyManager.java:121)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createDockerTarArchive(DockerAssemblyManager.java:75)
	at org.jolokia.docker.maven.BuildMojo.buildImage(BuildMojo.java:82)
	at org.jolokia.docker.maven.BuildMojo.executeInternal(BuildMojo.java:64)
	at org.jolokia.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:125)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more

**Comment by rhuss** [comment]
When you are using `<ports>` in the `<build>` sections, it's not about portmapping but about exposing ports. The contained list must be integer ports. It is only the ports section in the `<run>` config which is about port mapping. 

Makes this sense to you ?

**Comment by xcurry** [comment]
I knew I was missing something. Thanks for the explanation. Closing the issue.
