### ISSUE TITLE
docker:builder - Wonder if the error message can be improved if the project has no artifact

### ISSUE THREAD

**Issue by davsclaus** [rhuss/docker-maven-plugin#121]
When you have just created a new maven project, you may not have added any dependency yet. But added the maven-docker-plugin. And if you run a build it fails saying

```
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.11.2:build (default-cli) on project bar: Failed to create assembly for docker image: Error creating assembly archive docker: You must set at least one file. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jolokia:docker-maven-plugin:0.11.2:build (default-cli) on project bar: Failed to create assembly for docker image: Error creating assembly archive docker: You must set at least one file.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly for docker image: Error creating assembly archive docker: You must set at least one file.
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createAssemblyDirArchive(DockerAssemblyManager.java:159)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createDockerTarArchive(DockerAssemblyManager.java:65)
	at org.jolokia.docker.maven.BuildMojo.buildImage(BuildMojo.java:82)
	at org.jolokia.docker.maven.BuildMojo.executeInternal(BuildMojo.java:64)
	at org.jolokia.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:125)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.apache.maven.plugin.assembly.archive.ArchiveCreationException: Error creating assembly archive docker: You must set at least one file.
	at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:169)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createAssemblyDirArchive(DockerAssemblyManager.java:157)
	... 25 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: You must set at least one file.
	at org.codehaus.plexus.archiver.dir.DirectoryArchiver.execute(DirectoryArchiver.java:50)
	at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:930)
	at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:589)
	at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:165)
	... 26 more
```

For example with docker plugin configured as
```
 <plugin>
        <groupId>org.jolokia</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.11.2</version>
        <configuration>
          <images>
            <image>
              <name>${docker.image}</name>
              <build>
                <from>${docker.from}</from>
                <assembly>
                  <descriptorRef>${docker.assemblyDescriptorRef}</descriptorRef>
                </assembly>
              </build>
            </image>
          </images>
        </configuration>
      </plugin>
```

And the properties are
```
 <properties>
    <fabric8.label.container>java</fabric8.label.container>
    <fabric8.iconRef>icons/java.svg</fabric8.iconRef>
    <docker.registryPrefix>${env.DOCKER_REGISTRY}/</docker.registryPrefix>
    <docker.image>${docker.registryPrefix}fabric8/${project.artifactId}:${project.version}</docker.image>
    <maven.compiler.target>1.7</maven.compiler.target>
    <docker.port.container.jolokia>8778</docker.port.container.jolokia>
    <docker.from>fabric8/java</docker.from>
    <fabric8.label.group>mystuff</fabric8.label.group>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <docker.assemblyDescriptorRef>artifact-with-dependencies</docker.assemblyDescriptorRef>
    <maven.compiler.source>1.7</maven.compiler.source>
  </properties>
```

The error message got me baffled for a while, until I added some dependencies.

**Comment by jgangemi** [comment]
it looks like that message comes straight out of the assembly plugin.

**Comment by davsclaus** [comment]
Yeah, but wonder if the docker plugin can detect that if the assemblyDescriptorRef is artifact-with-dependencies, and that the pom.xml has no dependencies, then fail with a more appropriate error.

Also I have noticed that if you forget to run mvn install first, and do a mvn docker:build, then artifact-with-dependencies, builds a docker image, but your own artifact is NOT included. So maybe artifact-with-dependencies can be improved to validate that there is an own artifact to include as well.

**Comment by jgangemi** [comment]
did you have any source files when you did the first build? i would think the build would succeed if you had those even w/o any dependencies but i'd have to double check that.

the other behavior you describe exists outside of this plugin - you'd see the same behavior if you execute any specific maven goal outside the regular build lifecycle.

not saying those aren't good suggestions, just pointing out the behavior isn't specific to this plugin.

**Comment by davsclaus** [comment]
Not it was in fact a new project that just had the docker maven plugin added.

But if you build using mvn install then it would succeed. Its when you can mvn install docker:build it fails, and that may be understandable as there is no JAR file to include, but the error message is "hard for new users" to know what is the problem.

**Comment by jgangemi** [comment]
yeah - that makes sense. it's a little annoying that maven requires things to run in the lifecycle for them to work properly. i would like to see `initialize` invoked before directly running any of the docker goals but that's not possible (well - it may be by tapping into the lifecycle manager but it's not a quick thing).

we should probably add a little section to the docs for new users that indicate the steps that should be run when setting up a project for the first time. maybe an faq page would be good.

**Comment by davsclaus** [comment]
Yeah sure a FAQ entry would be fine, and you are welcome to close this ticket.

**Comment by rhuss** [comment]
The problem is, that the artifact itself is not added with `<useProjectArtifact>` if the `package` phase is not run during the build. I.e. for an empty pom.xml like below, `mvn package docker:build` should be used. E.g. if `<descriptorRef>artifact</descriptorRef>` is used, it will always fail if no package phase is run. 

I will have a look at the assembly plugin how it handles this situation, since this is really not optimal and  IMO the artifact should be added even without building it.

Here's a minimal pom.xml to reproduce it:

````xml
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.jolokia</groupId>
  <artifactId>assembly-test</artifactId>
  <version>0.0.1</version>

  <build>
    <plugins>
       <plugin>
        <groupId>org.jolokia</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.11.2</version>
        <configuration>
          <images>
            <image>
              <name>jolokia/assembly-test</name>
              <build>
                <assembly>
                  <descriptorRef>artifact</descriptorRef>
                </assembly>
              </build>
            </image>
          </images>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
````

**Comment by jgangemi** [comment]
but what happens if the artifact doesn't exist, how will it get added? wouldn't it be better to just bind `docker:build` to the package phase that way you're guaranteed the proper result?

**Comment by rhuss** [comment]
If you do so, `docker:build` will be called for every `mvn package` (e.g. also for `mvn clean install`). I believe we want it to be the other way round, `package` called implicitly with `docker:build`. Let me have a look, how the assembly plugin does its business.

**Comment by jgangemi** [comment]
well, yes but you really shouldn't be doing a 'package' for every build right?

i'm not sure calling `package` can be done but i am very curious to hear your findings. this is somewhat similar to my desire to have the `initialize` goal run before every `docker:*` command which would open the door to storing docker properties outside of the pom via the properties plugin (#52).

i think to accomplish this you'd need to swap out some part of the lifecycle manager/provider.

**Comment by rhuss** [comment]
Well, I have the same issue with the assembly plugin. With

````xml
    <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>2.4.1</version>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
      </plugin>
````

a `mvn package assembly:single` works, but a `mvn assembly:single` fails with very same error message that @davsclaus gets when using `docker:build` without another maven goal including the `package` phase. (`jar-with-dependencies` uses this [assembly descriptor](http://maven.apache.org/plugins-archives/maven-assembly-plugin-2.4.1/descriptor-refs.html#jar-with-dependencies)). When using `moduleSets` there is even an explicit warning in the [docs](http://maven.apache.org/plugins/maven-assembly-plugin/assembly.html#class_moduleSet).

AFAIR one can get over this by defining a new packaging type (and hence a new lifecycle), but I hope there will be an easier solution to directly call another plugin's goal from within a pluginn.

**Comment by rhuss** [comment]
[That](http://stackoverflow.com/questions/1427740/how-do-i-execute-a-set-of-goals-before-my-maven-plugin-runs/1427783#1427783) might help. I don't think there is a solution without a custom lifecycle (see also this [stackoverflow](http://stackoverflow.com/questions/16264059/maven-bind-plugin-execution-to-the-execution-of-another-plugin-not-to-a-lifecy))

**Comment by rhuss** [comment]
Arrgh, probably won't work since if we are using an own lifecycle we have to specify the concrete packaging plugin (jar, war, ear, ...) and this is something our plugin doesn't really know. But I'm looking further whether one can use role hints as well in the lifecycle.xml.

(Digging in to Plexus component files feels like archaeology ;-)

**Comment by jgangemi** [comment]
yeah - this is where maven falls down and ant doesn't. you would think there'd at least be a way to trigger the initialization phase.

seems like a lot of effort for what is probably not an issue for most if they already have experience w/ the assembly plugin. 

+1 for some better docs and maybe calling out the usage of the plugin and that the user should go read those docs if they aren't already familiar w/ them.

**Comment by rhuss** [comment]
Yes, you are probably right. I will enhance the docs accordingly.
