### ISSUE TITLE
From field is required, even when setting dockerFileDir

### ISSUE THREAD

**Issue by oferrero** [rhuss/docker-maven-plugin#201]
When using a *dockerFileDir*, the Dockerfile  within that directory is to be used as the base image, and the from field is basically ignored.  However, if one proceeds to remove the *from* field, the following error is received:

```java
Caused by: org.apache.maven.plugin.MojoExecutionException: No image 'busybox:latest' found
	at org.jolokia.docker.maven.AbstractDockerMojo.checkImageWithAutoPull(AbstractDockerMojo.java:387)
	at org.jolokia.docker.maven.BuildMojo.buildImage(BuildMojo.java:83)
	at org.jolokia.docker.maven.BuildMojo.executeInternal(BuildMojo.java:70)
	at org.jolokia.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:135)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
```

Basically, the *from* field should be optional when setting the *dockerFileDir*.

**Comment by rhuss** [comment]
You are right, that's a bug.
