### ISSUE TITLE
Got a NPE when tried to build an image with simple jar file

### ISSUE THREAD

**Issue by CyborTronik** [rhuss/docker-maven-plugin#250]
I have a spring boot application and I would like to make a container for it but got a null pointer exception for next config:
```
   <plugin>
                <groupId>org.jolokia</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.13.2</version>
                <configuration>
                    <images>
                        <image>
                            <alias>cdc</alias>
                            <name>example/cdc</name>
                            <build>
                                <from>java:8</from>
                                <volumes>
                                    <volume>${project.build.directory}</volume>
                                </volumes>
                                <ports>
                                    <port>8080</port>
                                </ports>
                                <entryPoint>
                                    <exec>
                                        <args>java</args>
                                        <args>-jar</args>
                                        <args>/${project.build.finalName}.jar</args>
                                        <args>-Dspring.profiles.active=integration-tests</args>
                                    </exec>
                                </entryPoint>
                            </build>
                            <run>
                                <ports>
                                    <port>8080:8080</port>
                               </ports>
                            </run>
                        </image>
                    </images>
                </configuration>
                <executions>
                    <execution>
                        <id>start</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <!-- "build" should be used to create the images with the
                                 artefacts -->
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

And got next logs:

```
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.13.2:build (start) on project competitive-data-collector: Execution start of goal org.jolokia:docker-maven-plugin:0.13.2:build failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jolokia:docker-maven-plugin:0.13.2:build (start) on project competitive-data-collector: Execution start of goal org.jolokia:docker-maven-plugin:0.13.2:build failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution start of goal org.jolokia:docker-maven-plugin:0.13.2:build failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createDockerTarArchive(DockerAssemblyManager.java:85)
	at org.jolokia.docker.maven.AbstractBuildSupporMojo.buildImage(AbstractBuildSupporMojo.java:79)
	at org.jolokia.docker.maven.BuildMojo.executeInternal(BuildMojo.java:36)
	at org.jolokia.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:168)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 

```

**Comment by jgangemi** [comment]
this is a dup of #236 and should be fixed in the next release.
