### ISSUE TITLE
Random exceptions after quick start/stop with log

### ISSUE THREAD

**Issue by mgurov** [rhuss/docker-maven-plugin#278]
Given the following configuration

````xml
      <plugin>
        <groupId>org.jolokia</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.13.3</version>
        <configuration>
          <images>
            <image>
              <name>busybox</name>
              <run>
                <cmd>echo hello</cmd>
                <log/>
              </run>
            </image>
          </images>
        </configuration>
      </plugin>
````

I can often observe 'NoClassDefFoundError' exceptions after a successful maven build, e.g. `mvn docker:start docker:stop` produces output like following:

````
[INFO] --- docker-maven-plugin:0.13.3:start (default-cli) @ docker-maven-runs ---
[INFO] DOCKER> [busybox] : Start container 66e58c2c1aa4
[INFO]
[INFO] --- docker-maven-plugin:0.13.3:stop (default-cli) @ docker-maven-runs ---
[INFO] DOCKER> [busybox] : Stop and remove container 66e58c2c1aa4
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.993 s
[INFO] Finished at: 2015-09-06T17:47:22+02:00
[INFO] Final Memory: 16M/173M
[INFO] ------------------------------------------------------------------------
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/joda/time/chrono/ZonedChronology$ZonedDurationField
	at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:107)
	at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:86)
	at org.joda.time.DateTimeUtils.getChronology(DateTimeUtils.java:283)
	at org.joda.time.format.DateTimeFormatter.selectChronology(DateTimeFormatter.java:942)
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:851)
	at org.jolokia.docker.maven.util.Timestamp.<init>(Timestamp.java:53)
	at org.jolokia.docker.maven.access.log.LogRequestor.callLogCallback(LogRequestor.java:142)
	at org.jolokia.docker.maven.access.log.LogRequestor.parseResponse(LogRequestor.java:121)
	at org.jolokia.docker.maven.access.log.LogRequestor.run(LogRequestor.java:97)
Caused by: java.lang.ClassNotFoundException: org.joda.time.chrono.ZonedChronology$ZonedDurationField
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 9 more
````

The reproducibility is not 100% and the stack trace differs from run to run. 

These exceptions are not observed if the `<log/>` section removed or I do `docker:start` without `docker:stop`.

Admittedly minor issue as the build succeeds.

**Comment by rhuss** [comment]
Are the varying stacktraces all around joda-time ? Might a synchronization issue, too.

I just upgraded to joda-time 2.8.3 (from 2.3) in branch `integration`. Could you check whether this fixes this issue ?

If not, we can try to sync the log statements, which could help, too.

**Comment by mgurov** [comment]
Most of them include joda time, but not all. Also with the current `integration` and upgraded joda-time.

````
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/jolokia/docker/maven/log/LogDispatcher$LogEntry
	at org.jolokia.docker.maven.log.LogDispatcher$1.log(LogDispatcher.java:69)
	at org.jolokia.docker.maven.access.log.LogRequestor.callLogCallback(LogRequestor.java:144)
	at org.jolokia.docker.maven.access.log.LogRequestor.parseResponse(LogRequestor.java:121)
	at org.jolokia.docker.maven.access.log.LogRequestor.run(LogRequestor.java:97)
Caused by: java.lang.ClassNotFoundException: org.jolokia.docker.maven.log.LogDispatcher$LogEntry
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 4 more
````
