### ISSUE TITLE
How do I filter files?

### ISSUE THREAD

**Issue by testn** [rhuss/docker-maven-plugin#282]
It looks like the configuration file does not provide a mechanism to filter the fileset with filter. Is there a way to do that? currently, it seems to look up for target/class/build.properties for that.

**Comment by jgangemi** [comment]
can you clarify your question? filtering works via the assembly configuration if you've enabled the flag.

**Comment by testn** [comment]
I can turn the filtering on. I just would like to specify the filter.properties file it should use.

**Comment by rhuss** [comment]
It use the Maven properties defined in the pom. You can read in properties with the [maven-properties-plugin](http://www.mojohaus.org/properties-maven-plugin/usage.html) if this is what you want.

**Comment by testn** [comment]
Does not seem to work... I got the following exception:

Caused by: java.io.IOException: Error filtering file 'java.io.InputStreamReader@3cb8c8ce': Error loading property file '.../target/classes/build.properties'
	at org.apache.maven.plugin.assembly.format.ReaderFormatter$1.transform(ReaderFormatter.java:134)
	at org.codehaus.plexus.components.io.resources.AbstractPlexusIoResourceCollection.getInputStream(AbstractPlexusIoResourceCollection.java:279)
	at org.codehaus.plexus.components.io.resources.Deferred.<init>(Deferred.java:45)
	at org.codehaus.plexus.components.io.resources.AbstractPlexusIoResourceCollection.resolve(AbstractPlexusIoResourceCollection.java:286)
	at org.codehaus.plexus.archiver.ArchiveEntry.<init>(ArchiveEntry.java:74)
	... 40 more

**Comment by testn** [comment]
sounds like i have to add

<build>
...
        <filters>
            <filter>${basedir}/src/main/docker/environment.properties</filter>
        </filters>
...
</build>
