### ISSUE TITLE
Test failing running data-jolokia-demo

### ISSUE THREAD

**Issue by jaloncad** [rhuss/docker-maven-plugin#296]
Hi, first some changes I've made in pom.xml to work without needing to deploy *.war flies in maven repository by hand.

```

<dependency>
      <groupId>org.jolokia</groupId>
      <artifactId>jolokia-war</artifactId>
      <version>${jolokia.version}</version>
      <type>war</type>
      <scope>system</scope>
      <systemPath>${absolutepath}/jolokia.war</systemPath>
    </dependency>
    <!-- Jolokia Integration Test Setup (registers some Test MBeans) -->
    <dependency>
      <groupId>org.jolokia</groupId>
      <artifactId>jolokia-it-war</artifactId>
      <version>${jolokia.version}</version>
      <type>war</type>
      <scope>system</scope>
      <systemPath>${absolutepath}/jolokia-it.war</systemPath>
    </dependency>
```

Running mvn verify and with boot2docker up ... I get:

```
Running org.jolokia.docker.maven.sample.jolokia.VersionIT
Checking URL: http://192.168.59.103:32780/jolokia
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.71 sec <<< FAILURE! - in org.jolokia.docker.maven.sample.jolokia.VersionIT
testVersion(org.jolokia.docker.maven.sample.jolokia.VersionIT)  Time elapsed: 1.644 sec  <<< ERROR!
com.jayway.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
```

Complete log ¿any idea?:

```
@jaloncad/Applications/Dev/idea/docker-maven-plugin/samples/data-jolokia-demo$ mvn verify                                                                                                    
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jolokia:docker-jolokia-demo:jar:0.13.4
[WARNING] 'dependencies.dependency.systemPath' for org.jolokia:jolokia-war:war should use a variable instead of a hard-coded path /Users/jaloncad/Downloads/jolokia.war @ line 49, column 19
[WARNING] 'dependencies.dependency.systemPath' for org.jolokia:jolokia-it-war:war should use a variable instead of a hard-coded path /Users/jaloncad/Downloads/jolokia-it.war @ line 58, column 19
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building docker-jolokia-demo 0.13.4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ docker-jolokia-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Applications/Dev/idea/docker-maven-plugin/samples/data-jolokia-demo/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ docker-jolokia-demo ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ docker-jolokia-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Applications/Dev/idea/docker-maven-plugin/samples/data-jolokia-demo/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ docker-jolokia-demo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Applications/Dev/idea/docker-maven-plugin/samples/data-jolokia-demo/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ docker-jolokia-demo ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ docker-jolokia-demo ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] 
[INFO] --- docker-maven-plugin:0.13.4:build (start) @ docker-jolokia-demo ---
[INFO] DOCKER> ... latest Pulling from busybox
[INFO] DOCKER> ... cfa753dfea5e Already exists
[INFO] DOCKER> ... d7057cb02084 Already exists
[INFO] DOCKER> ... Digest: sha256:16a2a52884c2a9481ed267c2d46483eac7693b813a63132368ab098a71303f8a
[INFO] DOCKER> ... Status: Image is up to date for busybox:latest
[INFO] Reading assembly descriptor: /Applications/Dev/idea/docker-maven-plugin/samples/data-jolokia-demo/src/main/docker/assembly.xml
[WARNING] The following patterns were never triggered in this artifact inclusion filter:
o  'org.jolokia:jolokia-war'

[WARNING] The following patterns were never triggered in this artifact inclusion filter:
o  'org.jolokia:jolokia-it-war'

[INFO] Copying files to /Applications/Dev/idea/docker-maven-plugin/samples/data-jolokia-demo/target/docker/jolokia/docker-jolokia-demo/0.13.4/build/maven
[INFO] Building tar: /Applications/Dev/idea/docker-maven-plugin/samples/data-jolokia-demo/target/docker/jolokia/docker-jolokia-demo/0.13.4/tmp/docker-build.tar
[INFO] DOCKER> Step 0 : FROM busybox:latest
[INFO] DOCKER> ---> d7057cb02084
[INFO] DOCKER> Step 1 : MAINTAINER docker-maven-plugin@jolokia.org
[INFO] DOCKER> ---> Using cache
[INFO] DOCKER> ---> bfd663267336
[INFO] DOCKER> Step 2 : VOLUME /maven
[INFO] DOCKER> ---> Using cache
[INFO] DOCKER> ---> b56b73bea081
[INFO] DOCKER> Step 3 : COPY maven /maven/
[INFO] DOCKER> ---> Using cache
[INFO] DOCKER> ---> 1cd6711c9038
[INFO] DOCKER> Successfully built 1cd6711c9038
[INFO] DOCKER> [jolokia/docker-jolokia-demo:0.13.4] "data": Built image 1cd6711c9038
[INFO] DOCKER> [jolokia/docker-jolokia-demo:0.13.4] "data": Tag with latest
[INFO] 
[INFO] --- docker-maven-plugin:0.13.4:start (start) @ docker-jolokia-demo ---
[INFO] DOCKER> [jolokia/docker-jolokia-demo:0.13.4] "data": Start container fabaf713d748
[INFO] DOCKER> ... latest Pulling from consol/tomcat-7.0
[INFO] DOCKER> ... 39bb80489af7 Already exists
[INFO] DOCKER> ... df2a0347c9d0 Already exists
[INFO] DOCKER> ... 7a3871ba15f8 Already exists
[INFO] DOCKER> ... a2703ed272d7 Already exists
[INFO] DOCKER> ... 1f8988f85bc1 Already exists
[INFO] DOCKER> ... 936fe0ee0a96 Already exists
[INFO] DOCKER> ... f03d673c8b0b Already exists
[INFO] DOCKER> ... d8d71741a6d9 Already exists
[INFO] DOCKER> ... beabd1eef902 Already exists
[INFO] DOCKER> ... a4a4c57a2889 Already exists
[INFO] DOCKER> ... 596678944aa2 Already exists
[INFO] DOCKER> ... ab27aadf1727 Already exists
[INFO] DOCKER> ... e29f50de8012 Already exists
[INFO] DOCKER> ... a03e9015f2ed Already exists
[INFO] DOCKER> ... 90190d5488f7 Already exists
[INFO] DOCKER> ... 4b418ac1d14b Already exists
[INFO] DOCKER> ... afaed0b06df7 Already exists
[INFO] DOCKER> ... 628d32d93e5b Already exists
[INFO] DOCKER> ... ed8498017b4c Already exists
[INFO] DOCKER> ... eb1153d2ed4d Already exists
[INFO] DOCKER> ... 9de164d532a0 Already exists
[INFO] DOCKER> ... edde299407b7 Already exists
[INFO] DOCKER> ... 9adab4371b5f Already exists
[INFO] DOCKER> ... f92c73f92596 Already exists
[INFO] DOCKER> ... 59f2425a422a Already exists
[INFO] DOCKER> ... bfc5f40a572a Already exists
[INFO] DOCKER> ... e88c09539e11 Already exists
[INFO] DOCKER> ... e88c09539e11 Already exists
[INFO] DOCKER> ... Digest: sha256:ed5dde276731bd3acdb50beb3d57e88851368352f3f13c7677a84ae7b9f70d37
[INFO] DOCKER> ... Status: Image is up to date for consol/tomcat-7.0:latest
[INFO] DOCKER> [consol/tomcat-7.0:latest] "server": Start container 9d2467a7a69a
00:13:51.435 server> Checking *.war in /maven
00:13:51.437 server> Linking /maven/*.war --> /opt/tomcat/webapps/*.war
00:13:52.280 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.280 server> INFO: Server version:        Apache Tomcat/7.0.62
00:13:52.283 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.283 server> INFO: Server built:          May 7 2015 17:14:55 UTC
00:13:52.287 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.287 server> INFO: Server number:         7.0.62.0
00:13:52.290 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.290 server> INFO: OS Name:               Linux
00:13:52.292 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.292 server> INFO: OS Version:            4.0.7-boot2docker
00:13:52.295 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.295 server> INFO: Architecture:          amd64
00:13:52.297 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.297 server> INFO: Java Home:             /usr/lib/jvm/java-7-openjdk-amd64/jre
00:13:52.303 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.303 server> INFO: JVM Version:           1.7.0_79-b14
00:13:52.303 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.303 server> INFO: JVM Vendor:            Oracle Corporation
00:13:52.309 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.309 server> INFO: CATALINA_BASE:         /opt/tomcat
00:13:52.313 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.313 server> INFO: CATALINA_HOME:         /opt/tomcat
00:13:52.318 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.318 server> INFO: Command line argument: -Djava.util.logging.config.file=/opt/tomcat/conf/logging.properties
00:13:52.319 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.319 server> INFO: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
00:13:52.323 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.323 server> INFO: Command line argument: -Xmx32m
00:13:52.326 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.326 server> INFO: Command line argument: -Djava.security.egd=file:/dev/./urandom
00:13:52.329 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.329 server> INFO: Command line argument: -Djava.endorsed.dirs=/opt/tomcat/endorsed
00:13:52.334 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.334 server> INFO: Command line argument: -Dcatalina.base=/opt/tomcat
00:13:52.338 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.338 server> INFO: Command line argument: -Dcatalina.home=/opt/tomcat
00:13:52.342 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.VersionLoggerListener log
00:13:52.342 server> INFO: Command line argument: -Djava.io.tmpdir=/opt/tomcat/temp
00:13:52.347 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
00:13:52.347 server> INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
00:13:52.485 server> Sep 23, 2015 10:13:52 PM org.apache.coyote.AbstractProtocol init
00:13:52.485 server> INFO: Initializing ProtocolHandler ["http-bio-8080"]
00:13:52.502 server> Sep 23, 2015 10:13:52 PM org.apache.coyote.AbstractProtocol init
00:13:52.502 server> INFO: Initializing ProtocolHandler ["ajp-bio-8009"]
00:13:52.509 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.Catalina load
00:13:52.509 server> INFO: Initialization processed in 711 ms
00:13:52.556 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.core.StandardService startInternal
00:13:52.556 server> INFO: Starting service Catalina
00:13:52.557 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.core.StandardEngine startInternal
00:13:52.557 server> INFO: Starting Servlet Engine: Apache Tomcat/7.0.62
00:13:52.577 server> Sep 23, 2015 10:13:52 PM org.apache.catalina.startup.HostConfig deployDirectory
00:13:52.577 server> INFO: Deploying web application directory /opt/apache-tomcat-7.0.62/webapps/host-manager
00:13:53.133 server> Sep 23, 2015 10:13:53 PM org.apache.catalina.startup.HostConfig deployDirectory
00:13:53.133 server> INFO: Deployment of web application directory /opt/apache-tomcat-7.0.62/webapps/host-manager has finished in 556 ms
00:13:53.140 server> Sep 23, 2015 10:13:53 PM org.apache.catalina.startup.HostConfig deployDirectory
00:13:53.140 server> INFO: Deploying web application directory /opt/apache-tomcat-7.0.62/webapps/manager
00:13:53.240 server> Sep 23, 2015 10:13:53 PM org.apache.catalina.startup.HostConfig deployDirectory
00:13:53.240 server> INFO: Deployment of web application directory /opt/apache-tomcat-7.0.62/webapps/manager has finished in 106 ms
00:13:53.244 server> Sep 23, 2015 10:13:53 PM org.apache.catalina.startup.HostConfig deployDirectory
00:13:53.244 server> INFO: Deploying web application directory /opt/apache-tomcat-7.0.62/webapps/ROOT
00:13:53.326 server> Sep 23, 2015 10:13:53 PM org.apache.catalina.startup.HostConfig deployDirectory
00:13:53.326 server> INFO: Deployment of web application directory /opt/apache-tomcat-7.0.62/webapps/ROOT has finished in 84 ms
00:13:53.331 server> Sep 23, 2015 10:13:53 PM org.apache.coyote.AbstractProtocol start
00:13:53.331 server> INFO: Starting ProtocolHandler ["http-bio-8080"]
00:13:53.347 server> Sep 23, 2015 10:13:53 PM org.apache.coyote.AbstractProtocol start
00:13:53.347 server> INFO: Starting ProtocolHandler ["ajp-bio-8009"]
00:13:53.351 server> Sep 23, 2015 10:13:53 PM org.apache.catalina.startup.Catalina start
00:13:53.351 server> INFO: Server startup in 839 ms
[INFO] DOCKER> [consol/tomcat-7.0:latest] "server": Waited on url http://192.168.59.103:32780/jolokia and on log out 'Server startup' 2089 ms
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:integration-test (integration-test) @ docker-jolokia-demo ---
[INFO] Failsafe report directory: /Applications/Dev/idea/docker-maven-plugin/samples/data-jolokia-demo/target/failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jolokia.docker.maven.sample.jolokia.VersionIT
Checking URL: http://192.168.59.103:32780/jolokia
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.71 sec <<< FAILURE! - in org.jolokia.docker.maven.sample.jolokia.VersionIT
testVersion(org.jolokia.docker.maven.sample.jolokia.VersionIT)  Time elapsed: 1.644 sec  <<< ERROR!
com.jayway.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
        at groovy.json.JsonLexer.nextToken(JsonLexer.java:82)
        at groovy.json.JsonLexer$nextToken.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at com.jayway.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:99)
        at com.jayway.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
        at com.jayway.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:85)
        at com.jayway.restassured.path.json.JsonPath$4$1.method(JsonPath.java:839)
        at com.jayway.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:874)
        at com.jayway.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:837)
        at com.jayway.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:917)
        at com.jayway.restassured.path.json.JsonPath.get(JsonPath.java:182)
        at org.jolokia.docker.maven.sample.jolokia.VersionIT.testVersion(VersionIT.java:32)


Results :

Tests in error: 
  VersionIT.testVersion:32 » JsonPath Failed to parse the JSON document

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] 
[INFO] --- docker-maven-plugin:0.13.4:stop (stop) @ docker-jolokia-demo ---
[INFO] DOCKER> [consol/tomcat-7.0:latest] "server": Stop and remove container 9d2467a7a69a
[INFO] DOCKER> [jolokia/docker-jolokia-demo:0.13.4] "data": Stop and remove container fabaf713d748
[INFO] 
[INFO] --- maven-failsafe-plugin:2.17:verify (verify) @ docker-jolokia-demo ---
[INFO] Failsafe report directory: /Applications/Dev/idea/docker-maven-plugin/samples/data-jolokia-demo/target/failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.404 s
[INFO] Finished at: 2015-09-24T00:13:56+02:00
[INFO] Final Memory: 28M/272M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.17:verify (verify) on project docker-jolokia-demo: There are test failures.
[ERROR] 
[ERROR] Please refer to /Applications/Dev/idea/docker-maven-plugin/samples/data-jolokia-demo/target/failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Rgds, 
Juan.

**Comment by rhuss** [comment]
The issue is, that the assembly used to build the docker image doesn't pick up your dependencies:

> [INFO] Reading assembly descriptor: /Applications/Dev/idea/docker-maven-plugin/samples/data-jolokia-demo/src/main/docker/assembly.xml
> [WARNING] The following patterns were never triggered in this artifact inclusion filter:
> o  'org.jolokia:jolokia-war'
> 
> [WARNING] The following patterns were never triggered in this artifact inclusion filter:
> o  'org.jolokia:jolokia-it-war'

The reason for that is, that you use `system` scope for the dependencies, which apparently the assembly plugin doesn't consider to be a dependency.

Since you want to include specific files anyway, I recommend to use a `<fileSet>` instead of a `<dependencySet>` in the assembly configuration of the plugin. Please refer to the `assembly-maven-plugin` for the detailed syntax.

**Comment by jaloncad** [comment]
Perfect!!! I tried with filesets and something went wrong, so I've came back to manually installation : mvn install:install-file -Dfile=./src/main/docker/demo/jolokia.war -DgroupId=org.jolokia -DartifactId=jolokia-war -Dversion=1.3.2-SNAPSHOT -Dpackaging=war

Thx, Juan.
