### ISSUE TITLE
enabling 'filtered' on 'files' in assembly descriptor yields NullPointerException

### ISSUE THREAD

**Issue by jgangemi** [rhuss/docker-maven-plugin#82]
example `assembly.xml` snippet

```xml
  <files>
    <file>
      <source>src/main/docker/app/startup.sh</source>
      <outputDirectory>/usr/local/bin</outputDirectory>
      <fileMode>0755</fileMode>
      <filtered>true</filtered>
    </file>
  </files>
```

relevant stacktrace

```
Caused by: java.lang.NullPointerException
	at org.apache.maven.plugin.assembly.format.ReaderFormatter.createReaderFilter(ReaderFormatter.java:81)
	at org.apache.maven.plugin.assembly.format.ReaderFormatter.access$000(ReaderFormatter.java:41)
	at org.apache.maven.plugin.assembly.format.ReaderFormatter$1.transform(ReaderFormatter.java:116)
	at org.apache.maven.plugin.assembly.archive.phase.FileItemAssemblyPhase$1.getInputStream(FileItemAssemblyPhase.java:130)
	at org.apache.maven.plugin.assembly.archive.phase.FileItemAssemblyPhase$Deferred.<init>(FileItemAssemblyPhase.java:166)
	at org.apache.maven.plugin.assembly.archive.phase.FileItemAssemblyPhase$1.<init>(FileItemAssemblyPhase.java:134)
	at org.apache.maven.plugin.assembly.archive.phase.FileItemAssemblyPhase.execute(FileItemAssemblyPhase.java:125)
	at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:162)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createArchiveFromAssembly(DockerAssemblyManager.java:126)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.create(DockerAssemblyManager.java:55)
	at org.jolokia.docker.maven.BuildMojo.buildImage(BuildMojo.java:66)
	at org.jolokia.docker.maven.BuildMojo.executeInternal(BuildMojo.java:58)
	at org.jolokia.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:136)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	... 20 more
```

this will require the `DockerAssemblyConfigurationSource` to return an implementation of `MavenReaderFilter`. i think this is a simple as returning an instance of `DefaultMavenReaderFilter`, i just nee to validate that.

**Comment by rhuss** [comment]
fixed in 0.11.2
