### ISSUE TITLE
NPE in DockerAssemblyConfigurationSource running docker:build if no assemblyDescriptorRef in pom.xml

### ISSUE THREAD

**Issue by davsclaus** [rhuss/docker-maven-plugin#85]
I have a bit trouble upgrading from 0.10.5 to 0.11.0 causing
https://github.com/fabric8io/fabric8/issues/3297

So I wonder if it was due we have a placeholder, so I tried to remove it all together
https://github.com/fabric8io/quickstarts/blob/master/quickstarts/java/camel-cdi/pom.xml#L178

Now I get a NPE in the plugin at
```
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.11.0:build (default-cli) on project quickstart-java-camel-cdi: Execution default-cli of goal org.jolokia:docker-maven-plugin:0.11.0:build failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jolokia:docker-maven-plugin:0.11.0:build (default-cli) on project quickstart-java-camel-cdi: Execution default-cli of goal org.jolokia:docker-maven-plugin:0.11.0:build failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.jolokia:docker-maven-plugin:0.11.0:build failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.jolokia.docker.maven.assembly.DockerAssemblyConfigurationSource.getDescriptors(DockerAssemblyConfigurationSource.java:34)
	at org.apache.maven.plugin.assembly.io.DefaultAssemblyReader.readAssemblies(DefaultAssemblyReader.java:95)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.extractAssembly(DockerAssemblyManager.java:138)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.createArchiveFromAssembly(DockerAssemblyManager.java:122)
	at org.jolokia.docker.maven.assembly.DockerAssemblyManager.create(DockerAssemblyManager.java:55)
	at org.jolokia.docker.maven.BuildMojo.buildImage(BuildMojo.java:66)
	at org.jolokia.docker.maven.BuildMojo.executeInternal(BuildMojo.java:58)
	at org.jolokia.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:136)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
```

**Comment by rhuss** [comment]
Did you update your pom.xml with the slightly [changed configuration syntax](https://github.com/rhuss/docker-maven-plugin/blob/master/doc/changelog.md) ? 

Nonetheless the NPE is a bug which I will ASAP.

**Comment by rhuss** [comment]
Please try to replace https://github.com/fabric8io/quickstarts/blob/master/quickstarts/java/camel-cdi/pom.xml#L178 with

```xml
<assembly>
    <descriptor>${docker.assemblyDescriptorRef}</descriptor>
</assembly>
```

**Comment by davsclaus** [comment]
Thanks @rhuss doing this change, I get a different error. Seems like it wants to read a `artifact-with-dependencies` file from my file system.

Here is the entire output from my shell.
```
davsclaus:~/workspace/quickstarts/quickstarts/java/camel-cdi (master)/$ mvn clean install org.jolokia:docker-maven-plugin:0.11.0:build
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Quickstart : Camel CDI 2.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ quickstart-java-camel-cdi ---
[INFO] Deleting /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ quickstart-java-camel-cdi ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ quickstart-java-camel-cdi ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ quickstart-java-camel-cdi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.1:compile (default-compile) @ quickstart-java-camel-cdi ---
[INFO] Compiling 2 source files to /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/classes
[INFO]
[INFO] --- fabric8-maven-plugin:2.0.25:json (json) @ quickstart-java-camel-cdi ---
[INFO] Configured with file: /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/classes/kubernetes.json
[INFO] Generated port mappings: {jolokia=io.fabric8.kubernetes.api.model.Port@2199a025[containerPort=8778,hostIP=<null>,hostPort=<null>,name=<null>,protocol=<null>,additionalProperties={}]}
[INFO] Generated env mappings: {}
[INFO] Attaching kubernetes json file: /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/classes/kubernetes.json to the build
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ quickstart-java-camel-cdi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.1:testCompile (default-testCompile) @ quickstart-java-camel-cdi ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ quickstart-java-camel-cdi ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ quickstart-java-camel-cdi ---
[INFO] Building jar: /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/quickstart-java-camel-cdi.jar
[INFO]
[INFO] --- jube-maven-plugin:2.0.25:build (default) @ quickstart-java-camel-cdi ---
[INFO] Generating Jube image 192.168.59.103:5000/fabric8/quickstart-java-camel-cdi:2.2-SNAPSHOT from base image fabric8/java
[INFO] Assembly reference: artifact-with-dependencies
Env vars: {MAIN=org.apache.camel.cdi.Main, SERVICE=quickstart-java-camel-cdi, SERVICE_NAME=Quickstart : Camel CDI}
[INFO] Looking up Jube: fabric8:java:zip:image:2.0.25
[INFO] Looking up Jube: io.fabric8.jube.images.fabric8:java:zip:image:2.0.25
/Users/davsclaus/.m2/repository/io/fabric8/jube/images/fabric8/java/2.0.25/java-2.0.25-image.zip
[INFO] File: /Users/davsclaus/.m2/repository/io/fabric8/jube/images/fabric8/java/2.0.25/java-2.0.25-image.zip
[INFO] Unpacking base image /Users/davsclaus/.m2/repository/io/fabric8/jube/images/fabric8/java/2.0.25/java-2.0.25-image.zip to build dir: /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/jube
[INFO] Copying files to /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/jube-assembly/maven
[INFO] Created image zip: /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/quickstart-java-camel-cdi-2.2-SNAPSHOT-image.zip
[INFO]
[INFO] --- fabric8-maven-plugin:2.0.25:zip (zip) @ quickstart-java-camel-cdi ---
[INFO] Generated icon file /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/generated-app/quickstart-java-camel-cdi/icon.svg from icon reference: icons/camel.svg
[INFO] zipping file quickstart-java-camel-cdi/data/message1.txt
[INFO] zipping file quickstart-java-camel-cdi/data/message2.txt
[INFO] zipping file quickstart-java-camel-cdi/fabric8.properties
[INFO] zipping file quickstart-java-camel-cdi/icon.svg
[INFO] zipping file quickstart-java-camel-cdi/kubernetes.json
[INFO] zipping file quickstart-java-camel-cdi/README.md
[INFO] zipping file quickstart-java-camel-cdi/Summary.md
[INFO] Created app zip file: /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/quickstart-java-camel-cdi-2.2-SNAPSHOT-app.zip
[INFO] Last project done. Now generating aggregated zips for the entire project(s).
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ quickstart-java-camel-cdi ---
[INFO] Installing /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/quickstart-java-camel-cdi.jar to /Users/davsclaus/.m2/repository/io/fabric8/jube/images/fabric8/quickstart-java-camel-cdi/2.2-SNAPSHOT/quickstart-java-camel-cdi-2.2-SNAPSHOT.jar
[INFO] Installing /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/pom.xml to /Users/davsclaus/.m2/repository/io/fabric8/jube/images/fabric8/quickstart-java-camel-cdi/2.2-SNAPSHOT/quickstart-java-camel-cdi-2.2-SNAPSHOT.pom
[INFO] Installing /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/classes/kubernetes.json to /Users/davsclaus/.m2/repository/io/fabric8/jube/images/fabric8/quickstart-java-camel-cdi/2.2-SNAPSHOT/quickstart-java-camel-cdi-2.2-SNAPSHOT-kubernetes.json
[INFO] Installing /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/quickstart-java-camel-cdi-2.2-SNAPSHOT-image.zip to /Users/davsclaus/.m2/repository/io/fabric8/jube/images/fabric8/quickstart-java-camel-cdi/2.2-SNAPSHOT/quickstart-java-camel-cdi-2.2-SNAPSHOT-image.zip
[INFO] Installing /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/quickstart-java-camel-cdi-2.2-SNAPSHOT-app.zip to /Users/davsclaus/.m2/repository/io/fabric8/jube/images/fabric8/quickstart-java-camel-cdi/2.2-SNAPSHOT/quickstart-java-camel-cdi-2.2-SNAPSHOT-app.zip
[INFO]
[INFO] --- docker-maven-plugin:0.11.0:build (default-cli) @ quickstart-java-camel-cdi ---
[INFO] Reading assembly descriptor: /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/src/main/docker/artifact-with-dependencies
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.260 s
[INFO] Finished at: 2015-02-04T16:05:35+01:00
[INFO] Final Memory: 36M/405M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.11.0:build (default-cli) on project quickstart-java-camel-cdi: Error reading assembly: Error locating assembly descriptor: /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/src/main/docker/artifact-with-dependencies
[ERROR]
[ERROR] [1] [INFO] Searching for file location: /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/src/main/docker/artifact-with-dependencies
[ERROR]
[ERROR] [2] [INFO] File: /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/src/main/docker/artifact-with-dependencies does not exist.
[ERROR]
[ERROR] [3] [INFO] File: /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/src/main/docker/artifact-with-dependencies does not exist.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
davsclaus:~/workspace/quickstarts/quickstarts/java/camel-cdi (master)/$
```

**Comment by jgangemi** [comment]
if you are using a descriptorRef, you have to use the `descriptorRef` element.

**Comment by davsclaus** [comment]
I was under the impression that the docker-maven-plugin has a set of _out of the box_ assembly descriptors.

So in 0.10.4 and 0.10.5 version of the plugin we refer to a descriptorRef with the name `artifact-with-dependencies`. Now doing no other change than what @rhuss suggest seems to not be able to find that descriptor ref.

Documentation at
https://github.com/rhuss/docker-maven-plugin/blob/master/doc/manual.md#build-assembly

says -->

descriptorRef is an alias to a predefined assembly descriptor. The available aliases are also described in the Docker Assembly section.

Which links to -> 
https://github.com/rhuss/docker-maven-plugin/blob/master/doc/manual.md#docker-assembly

-->
artifact-with-dependencies will copy your project's artifact and all its dependencies

But I guess its maybe our level of indirection that fools 0.11.0, maybe if I try hardcoding the ref to `artifact-with-dependencies` instead of using the property placeholder ${ } style.

**Comment by davsclaus** [comment]
eg we would like this level of indirection, as then we can configure everything in the top of the pom.xml, and people dont have to go hunt down in various build -> plugin sections of the pom files.

**Comment by davsclaus** [comment]
No this fails as well

```
-                <assemblyDescriptorRef>${docker.assemblyDescriptorRef}</assemblyDescriptorRef>
+                <assembly>
+                  <descriptor>artifact-with-dependencies</descriptor>
+                </assembly>
```

**Comment by jgangemi** [comment]
you need to use `descriptorRef`, not `descriptor`.

**Comment by davsclaus** [comment]
@jgangemi ah yeah I also just spotted that - sorry for the noise

**Comment by davsclaus** [comment]
Yep and the level of indirection also works. Okay got it.

**Comment by jgangemi** [comment]
:+1:
